services:
  wishlist:
    image: charmcli/wishlist:latest
    container_name: wishlist
    ports:
      - "2222:22"
    volumes:
      - ./wishlist:/.wishlist
      - ./cache:/root/.cache
    command: serve